### ISSUE TITLE
Search should recognize tags

### ISSUE THREAD

**Issue by phildini** [phildini/logtacts#3]
> (This is an `idea` issue. This should be a place for discussion, and then individual issues are filed for each outcome of the discussion)

At basic, search should search the tags on a contact.

A more advanced version of this would have search prompting for known tags with lookahead.

A thing @paulproteus wants, which I think is good: The ability to tag someone with "location:sfbay" and have it return just the people who have been tagged with that.

**Comment by paulproteus** [comment]
re: `location:sfbay`:

My thinking here is that this can be a string tag like any other.

Use-case:

- As a contact book owner,

- I can invite someone to my logtacts instance, and

- They can add information using a fixed set of tags for locations, or add them, to categorize people that have logtacts entries,

- So that when yet *other* people visit the logtacts instance, they can search people by these location tags.

**Comment by paulproteus** [comment]
Per #7 it would be cool if the search interface rendered these tags as chips, too.

**Comment by phildini** [comment]
With 876ed3e63ea0ce05be36eaa732c9d1a5fa24845d I'm calling this done.

**Comment by paulproteus** [comment]
Yippeee!​
